---
networks:
  monitoring:
    driver: bridge

volumes:
  prometheus_data: {}
  grafana-storage: {}

services:
  plex:
    image: lscr.io/linuxserver/plex:latest
    container_name: plex
    network_mode: host
    environment:
      - PUID=1100
      - PGID=1100
      - TZ=Etc/UTC
      - VERSION=docker
    volumes:
      - /host/config/plex:/config
      - /host/media:/data/media
    restart: unless-stopped

  transmission-openvpn:
    image: haugene/transmission-openvpn
    container_name: transmission-openvpn
    cap_add:
      - NET_ADMIN
    sysctls:
      - 'net.ipv6.conf.all.disable_ipv6=0'
    volumes:
      - '/host/media/:/data'
      - '/host/config/transmission-openvpn/:/config'
    environment:
      - PUID=1100
      - PGID=1100
      - TZ=Etc/UTC      
      - OPENVPN_PROVIDER=MULLVAD
      - OPENVPN_CONFIG=cz_prg
      - OPENVPN_USERNAME=${VPN_ID}
      - OPENVPN_PASSWORD=m
      - LOCAL_NETWORK=${LOCAL_NETWORK}
    logging:
      driver: json-file
      options:
        max-size: 10m
    ports:
      - '19091:9091'

  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=1100
      - PGID=1100
      - TZ=Etc/UTC
    volumes:
      - /host/config/radarr:/config
      - /host/media/movies:/movies #optional
      - /host/media:/downloads #optional
    ports:
      - 7878:7878
    restart: unless-stopped

  node-exporter:
    image: prom/node-exporter:latest
    container_name: node-exporter
    restart: unless-stopped
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.rootfs=/rootfs'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)'
    expose:
      - 9100
    networks:
      - monitoring

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    restart: unless-stopped
    volumes:
      - /host/config/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--web.enable-lifecycle'
    expose:
      - 9090
    networks:
      - monitoring

  grafana:
    image: grafana/grafana-enterprise
    container_name: grafana
    restart: unless-stopped
    expose:
      - '3000'
    networks:
      - monitoring
    volumes:
      - grafana-storage:/var/lib/grafana

  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    network_mode: host
    environment:
      #DNSMASQ_USER: root 
      #PIHOLE_UID: 0
      INTERFACE: wlx90de8004fdad
      PUID: 1100
      PGID: 1100
      TZ: 'EST'
      WEBPASSWORD: ${PIHOLE_PASSWORD}
    volumes:
      - '/host/config/pihole/etc-pihole:/etc/pihole'
      - '/host/config/pihole/etc-dnsmasq.d:/etc/dnsmasq.d'
    cap_add:
      - NET_ADMIN # Required if you are using Pi-hole as your DHCP server, else not needed
    restart: unless-stopped
